#!/bin/bash
# ============================================================
# NAMESPACE: Launcher
# DESCRIPTION: application entrypoint (minimal logic)
# ============================================================


# shellcheck source=/dev/null
source "./app/core/bootstrap.sh"

# run bootstrap and start the application
appBootstrap && appRun