#!/bin/bash
# ============================================================
# NAMESPACE: Launcher
# DESCRIPTION: application entrypoint (minimal logic)
# ============================================================

# trap ctrl + c / esc events
trap processTerminated SIGINT SIGTERM

# shellcheck source=/dev/null
source "./app/core/bootstrap.sh"

# run bootstrap and start the application
appBootstrap && appRun